20110809
========

doctemplates
------------

Opened ticket :doc:`/tickets/46`, but we'll let wait 
this ticket until real need grows because it's not trivial.

One bug less
------------

The following traceback happened when user left the job field of a contract empty::

  File "l:\snapshots\django\django\core\handlers\base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "t:\hgwork\lino\lino\ui\extjs3\ext_ui.py", line 983, in api_list_view
    return self.form2obj_and_save(request,rh,request.POST,instance,True)

  File "t:\hgwork\lino\lino\ui\extjs3\ext_ui.py", line 855, in form2obj_and_save
    elem.full_clean()

  File "t:\hgwork\lino\lino\modlib\jobs\models.py", line 417, in full_clean
    self.hourly_rate = self.job.hourly_rate

  File "l:\snapshots\django\django\db\models\fields\related.py", line 302, in __get__
    raise self.field.rel.to.DoesNotExist


Continue on UnicodeError while saving uploaded files with non-ascii chars
-------------------------------------------------------------------------

Here is again our traceback::

  Traceback:
  File "/var/snapshots/django/django/core/handlers/base.py" in get_response
    111.                         response = callback(request, *callback_args, **callback_kwargs)
  File "/var/snapshots/lino/lino/ui/extjs3/ext_ui.py" in api_list_view
    982.                 rh.report.handle_uploaded_files(request,instance)
  File "/var/snapshots/lino/lino/reports.py" in f
    715.         return m(obj,request)
  File "/var/snapshots/lino/lino/mixins/uploadable.py" in handle_uploaded_files
    85.         ff.save(uf.name,uf,save=False)
  File "/var/snapshots/django/django/db/models/fields/files.py" in save
    90.         self.name = self.storage.save(name, content)
  File "/var/snapshots/django/django/core/files/storage.py" in save
    48.         name = self.get_available_name(name)
  File "/var/snapshots/django/django/core/files/storage.py" in get_available_name
    74.         while self.exists(name):
  File "/var/snapshots/django/django/core/files/storage.py" in exists
    233.         return os.path.exists(self.path(name))
  File "/usr/lib/python2.6/genericpath.py" in exists
    18.         st = os.stat(path)
    
    
One problem is that Django doesn't recognize our POST 
request 
as `is_ajax <https://docs.djangoproject.com/en/dev/ref/request-response/#django.http.HttpRequest.is_ajax>`_ and thus the traceback is difficult to see.